x-logging: &default-logging
  driver: loki
  options:
    loki-url: '${LOKI_URL:-http://localhost:3100/api/prom/push}'
    loki-pipeline-stages: |
      - multiline:
          firstline: '^\d{4}-\d{2}-\d{2} \d{1,2}:\d{2}:\d{2}'
          max_wait_time: 3s
      - regex:
          expression: '^(?P<time>\d{4}-\d{2}-\d{2} \d{1,2}:\d{2}:\d{2},d{3}) (?P<message>(?s:.*))$$'

services:
  loki:
    image: grafana/loki:3.0.0
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "3100:3100"

  prometheus:
    image: prom/prometheus:v2.51.2
    ports:
      - "9090:9090"
    volumes:
      - ./obs/prometheus:/workspace
    command:
      - --config.file=/workspace/${PROMETHEUS_CONFIG:-prometheus.yml}
      - --enable-feature=exemplar-storage
    logging: *default-logging
    depends_on:
      - loki

  tempo:
    image: grafana/tempo:2.4.1
    command: [ "--target=all", "--storage.trace.backend=local", "--storage.trace.local.path=/var/tempo", "--auth.enabled=false" ]
    ports:
      - "4317:4317"
      - "4318:4318"
    logging: *default-logging
    depends_on:
      - loki

  grafana:
    image: grafana/grafana:10.4.2
    ports:
      - "3122:3000"
    volumes:
      - ./obs/grafana/:/etc/grafana/provisioning/datasources
      - ./obs/dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml
      - ./obs/dashboards:/etc/grafana/dashboards
    logging: *default-logging
    depends_on:
      - loki
      - tempo
      - prometheus

networks:
  default:
    name: observability_net
    external: true